trigger:
- main

pool:
  name: devops-agent-pool

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'

- task: Npm@1
  inputs:
    command: 'install'
    workingDir: '$(System.DefaultWorkingDirectory)'

- script: |
    npm run build
  displayName: 'Build App'
  workingDirectory: '$(System.DefaultWorkingDirectory)'

- script: |
    echo %CD%
    dir
  displayName: 'Check Files'