trigger:
- main

pool:
  name: devops-agent-pool

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '16.x'

- script: |
    npm ci
  displayName: 'Install Dependencies'

- script: |
    npm install -g sonarqube-scanner
    sonar-scanner ^
      -Dsonar.projectKey=todo-app ^
      -Dsonar.sources=. ^
      -Dsonar.host.url=http://<YOUR-IP>:9000 ^
      -Dsonar.login=<YOUR-TOKEN>
  displayName: 'Run SonarQube Scan'

- script: |
    npm run build
  displayName: 'Build App'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(System.DefaultWorkingDirectory)/build'
    ArtifactName: 'drop'